/**
 * CloudNote
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2002 { 
    currentPage: any;
    data: any;
    firstPageUrl: any;
    from: any;
    lastPageUrl: any;
    lastPage: any;
    /**
     * Generated paginator links.
     */
    links: any;
    nextPageUrl: any;
    /**
     * Base path for paginator generated URLs.
     */
    path: any;
    /**
     * Number of items shown per page.
     */
    perPage: any;
    prevPageUrl: any;
    /**
     * Number of the last item in the slice.
     */
    to: any;
    /**
     * Total number of items being paginated.
     */
    total: any;
}